### ISSUE TITLE
Backslash in file names causes FTPListParseException

### ISSUE THREAD

**Issue by davidekholm** [asbachb/ftp4j#8]
A backslash in a filename on the server causes FTPListParseException with the Unix list parser.

**Comment by asbachb** [comment]
I need more information like a stacktrace, parameters, file lists, etc.

**Comment by davidekholm** [comment]
Here is what I've got from the customer who reported this:

Caused by: it.sauronsoftware.ftp4j.FTPListParseException
at it.sauronsoftware.ftp4j.FTPClient.list(FTPClient.java:1990)
at info.cqs.remotefs.ftp.Ftp4jAdapter.getFiles(Ftp4jAdapter.java:341)
